# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-23 17:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('winner', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('min_price', models.DecimalField(decimal_places=2, default=1.0, help_text=b'Starting price', max_digits=10)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2017, 9, 26, 17, 49, 10, 321218, tzinfo=utc), help_text=b'format: YYYY-MM-DD HH:MM')),
                ('active', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('due', models.BooleanField(default=False)),
                ('adjudicated', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, default=1.0, help_text=b'raise bid with this amount', max_digits=10)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netstore.Auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bid'],
            },
        ),
    ]
