# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('netstore', '0002_auto_20171012_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='version',
            field=models.CharField(default='defaultforexistingrows', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 16, 33, 33, 716345, tzinfo=utc), help_text=b'format: YYYY-MM-DD HH:MM'),
        ),
    ]
